#!/bin/bash
#
# Runs as root. Drop privileges.
#
# Capture kill/term signal and send SIGINT to gracefully shutdown TFH server.
PROCESS_WAIT_TIME=25
WATCHDOG_TIME=300

#function shutdown() {
  #echo 'Shutting down server ...'
  #if [ "$(pgrep -n Conan)" != '' ]; then
    #echo "Sending SIGINT to Conan server (max ${PROCESS_WAIT_TIME} secs) ..."
    #kill -SIGINT `pgrep -n Conan`
    #sleep ${PROCESS_WAIT_TIME}
  #fi
  #if [ "$(pgrep wine)" != '' ]; then
    #echo "Sending SIGINT to wine processes (max ${PROCESS_WAIT_TIME} sec) ..."
    #kill -SIGINT `pgrep wine`
    #sleep ${PROCESS_WAIT_TIME}
  #fi
  #exit 0
#}
#trap shutdown SIGINT SIGKILL SIGTERM

function start_server() {
  WINEARCH=win32
  cp ./server.cfg ./server/config/server.cfg
  su - steam -c "${SERVER_DIR}/LobbyExe.exe"
}

function watch_server() {
  if ps aux | grep [L]obbyExe > /dev/null; then
    echo 'Server is running ...'
  else
    echo 'Starting server ...'
    start_server &
  fi
}

while true; do
  watch_server
  # background and using wait enables trap capture.
  sleep ${WATCHDOG_TIME} &
  wait
done
